[package]
name = "hrobot"
description = "Unofficial Hetzner Robot API client"
keywords = ["hetzner", "robot", "api", "client"]
repository = "https://github.com/MathiasPius/hrobot-rs"
version = "0.1.7"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.74"
serde_with = "1.12.0"
urlencoding = "2.1.0"

[dependencies.reqwest]
version = "0.11.9"
default-features = false
features = ["json", "multipart", "rustls-tls", "blocking"]

[dev-dependencies]
env_logger = "0.9.0"
dotenv = "0.15.0"
serial_test = "0.6.0"