[package]
name = "hrobot"
description = "Unofficial Hetzner Robot API client"
keywords = ["hetzner", "robot", "api", "client"]
repository = "https://github.com/MathiasPius/hrobot-rs"
version = "0.1.12"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "2"
urlencoding = "2"
thiserror = "1"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "multipart", "rustls-tls", "blocking"]

[dev-dependencies]
env_logger = "0.10"
dotenvy = "0.15"
serial_test = "1"
