[package]
name = "hrobot"
description = "Unofficial Hetzner Robot API client"
keywords = ["hetzner", "robot", "api", "client"]
repository = "https://github.com/MathiasPius/hrobot-rs"
version = "0.1.14"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
thiserror = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_html_form = "0.2.1"

base64 = "0.21.2"
hyper = "0.14.27"
urlencoding = "2"

async-trait = { version = "0.1.71", optional = true }
hyper-rustls = { version = "0.24.1", optional = true }

[dev-dependencies]
tracing-subscriber = "0.3.17"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
serial_test = "2"

[features]
default = ["hyper-client"]
async = ["dep:async-trait"]
hyper-client = ["async", "hyper/client", "hyper/http1", "dep:hyper-rustls"]
